#!/bin/bash
ant
echo -e "\n"
java -jar dist/bin/xcge.jar schema/po.xsd rules/pofail1.xml
echo -e "\n"
java -jar dist/bin/xcge.jar schema/po.xsd rules/pofail2.xml
echo -e "\n"
java -jar dist/bin/xcge.jar schema/po.xsd rules/pofail3.xml

